#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server.

file_path="$1"
server_ip=$2
server_username=$3

if [[ $# -lt 3 ]]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [[ $# -eq 3 ]]
then
    scp -o StrictHostKeyChecking=no "$file_path" "$server_username@$server_ip:/~"
else
    ssh_path=$4
    scp -o StrictHostKeyChecking=no -i "$ssh_path" "$file_path" "$server_username@$server_ip:/~"
fi