#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to respect requirements.

sudo su
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx start

rm /var/www/html/*
echo "Hello World!">/var/www/html/index.html