#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to respect requirements.

sudo su
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx restart
