#!/usr/bin/env bash
# A Bash script that configures Nginx server so that /redirect_me is redirecting to another page.

sudo su
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx start

rm /var/www/html/*
echo "Hello World!">/var/www/html/index.html

sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" "/etc/nginx/sites-available/default"
service nginx start