#!/usr/bin/env bash
# A Bash script that configures Nginx server so that /redirect_me is redirecting to another page.

sudo su
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx start

rm /var/www/html/*
echo "Hello World!">/var/www/html/index.html

echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name domain.com;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }}" > /etc/nginx/sites-available/redirect_me
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
service nginx start