#!/usr/bin/env bash
# installs Nginx server, redirects /redirect_me and customizes 404 not found

sudo apt-get -y update
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/error404.html
sudo sed -i '/server_name _;/a\\terror_page 404 /error404.html;' /etc/nginx/sites-available/default
sudo service nginx restart