#!/usr/bin/env bash
# installs Nginx server, redirects /redirect_me and customizes 404 not found

sudo su
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i '/server_name _;/a\\terror_page 404 /error404.html;' /etc/nginx/sites-available/default
service nginx restart
