#!/usr/bin/env bash
# A script that configures a new Ubuntu machine to respect above requirements

sudo apt-get -y update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.9

sudo apt-get install -y haproxy=2.9.\*

text_to_replace="
frontend myfrontend
  mode  http
  bind  :80
  default_backend  web_servers

backend web_servers
  mode http
  balance roundrobin
  server 417777-web-01 54.174.144.6:80 check
  server 417777-web-02 34.229.137.175:80 check
"
echo "ENABLED=1" >  /etc/default/haproxy
sed -i "N;#backend.*#a#backend web_servers\n\tmode http#" /etc/haproxy/haproxy.cfg
