#!/usr/bin/env bash
# script that gets Apache to run on the container and to return a page containing Hello Holberton when querying the root of it

apt-get -y update
apt-get -y install apache2
sudo service apache2 start